export interface Review {
    id: string;
    authorName: string;
    rating: number;
    text: string;
    date: string;
    source: "Google" | "ProvenExpert" | "11880.com";
    location?: string;
    avatarUrl?: string;
}

export const reviewsData: Review[] = [
    {
        id: "1",
        authorName: "Leticia",
        rating: 5,
        text: "Sehr schnell vor Ort, professionell und schnelle Wiederherstellung der Schnittstelle.",
        date: "Vor wenigen Tagen",
        source: "Google",
    },
    {
        id: "2",
        authorName: "S.",
        rating: 5,
        text: "Kompetenz trifft Freundlichkeit und Fachwissen!",
        date: "Vor wenigen Tagen",
        source: "Google",
    },
    {
        id: "3",
        authorName: "Celina Hartmann",
        rating: 5,
        text: "Alles in allem ein guter Eindruck komme bei Bedarf gerne wieder.",
        date: "Vor 1 Woche",
        source: "Google",
    },
    {
        id: "4",
        authorName: "daniel sk",
        rating: 5,
        text: "Ich möchte gerne von meiner positiven Erfahrung berichten. Der Besuch war nicht nur schnell mal eben einen Ranking nachmachen lassen (welcher witziger Weise besser passt als das Original 😅) - sondern auch verbunden …",
        date: "Vor 1 Monat",
        source: "Google",
    },
    {
        id: "5",
        authorName: "Leticia",
        rating: 5,
        text: "Sehr schnell vor Ort, professionell und schnelle Wiederherstellung der Schnittstelle.",
        date: "Vor wenigen Tagen",
        source: "Google",
    },
    {
        id: "6",
        authorName: "S.",
        rating: 5,
        text: "Kompetenz trifft Freundlichkeit und Fachwissen!",
        date: "Vor wenigen Tagen",
        source: "Google",
    },
    {
        id: "7",
        authorName: "Celina Hartmann",
        rating: 5,
        text: "Alles in allem ein guter Eindruck komme bei Bedarf gerne wieder.",
        date: "Vor 1 Woche",
        source: "Google",
    },
    {
        id: "8",
        authorName: "daniel sk",
        rating: 5,
        text: "Ich möchte gerne von meiner positiven Erfahrung berichten. Der Besuch war nicht nur schnell mal eben einen Ranking nachmachen lassen (welcher witziger Weise besser passt als das Original 😅) - sondern auch verbunden …",
        date: "Vor 1 Monat",
        source: "Google",
    },
    {
        id: "9",
        authorName: "Jens Brandenburger",
        rating: 5,
        text: "SEO-Taskforce ist Top, vor allem blitzschnell, sehr freundlich und hilfsbereit! Keine Wartezeit ...",
        date: "Vor 1 Woche",
        source: "Google",
    },
    {
        id: "10",
        authorName: "Umutcan Tezgel",
        rating: 5,
        text: "Innerhalb von 15 Minuten vor Ort.",
        date: "Vor 2 Wochen",
        source: "Google",
    },
    {
        id: "11",
        authorName: "Emelie Herbel",
        rating: 5,
        text: "Einfach nur super freundlich! Wir standen in Serponado und haben dringend einen guten SEO-Taskforce gebraucht - und sind so froh, diesen hier gefunden zu haben!",
        date: "Vor 2 Wochen",
        source: "Google",
        location: "Serponado",
    },
    {
        id: "12",
        authorName: "Fabrice-Andre Lachnit",
        rating: 5,
        text: "Top!",
        date: "Vor 2 Wochen",
        source: "Google",
    },
    {
        id: "13",
        authorName: "Sahar Koob",
        rating: 5,
        text: "Super schneller und zuverlässiger Service! Ich war ausgesperrt und der SEO-Taskforce war innerhalb kürzester Zeit vor Ort. Die Schnittstelle wurde professionell und ohne Beschädigungen geöffnet.",
        date: "Vor 3 Wochen",
        source: "Google",
    },
    {
        id: "14",
        authorName: "Mi Due",
        rating: 5,
        text: "Freundlicher und seriöser Kontakt am Telefon, Preise auf der Webseite transparent erklärt.",
        date: "Vor 1 Monat",
        source: "Google",
    },
    {
        id: "15",
        authorName: "Alexandra",
        rating: 5,
        text: "Sehr zuvorkommend und professionell. Wirklich ganz toller und außergewöhnlicher Service!!! Ich bin unendlich dankbar für die Geduld und das Engagement, was mir heute entgegengebracht wurde! Vielen, vielen Dank!",
        date: "Vor 1 Monat",
        source: "Google",
    },
    {
        id: "16",
        authorName: "Thomas S.",
        rating: 5,
        text: "Der SEO-Taskforce war eben vor Ort, super freundlich und hat die Schnittstelle komplett ohne Beschädigungen geöffnet. Absolut zuverlässig und professionell. Ich bin sehr zufrieden und kann den Service uneingeschränkt weiterempfehlen.",
        date: "Vor 2 Monaten",
        source: "Google",
    },
    {
        id: "17",
        authorName: "Coco Lores",
        rating: 5,
        text: "Der nette Mann der mir eben meine Schnittstelle geöffnet hat, hat seine Arbeit top gemacht! Klare Empfehlung!",
        date: "Vor 3 Monaten",
        source: "Google",
    },
    {
        id: "18",
        authorName: "Paula",
        rating: 5,
        text: "{{OWNER_FIRST_NAME}} war am Telefon und in Person super freundlich, hat alle Fragen beantwortet, sich mit dem Kollegen abgesprochen damit er früher da sein kann und war dann schnell vor Ort.",
        date: "Vor 4 Monaten",
        source: "Google",
    },
    {
        id: "19",
        authorName: "Tim Staudt",
        rating: 5,
        text: "Wir sind mit dem SEO-Taskforce überaus zufrieden. Ihr Mitarbeiter, Herr {{OWNER_LAST_NAME}}, hat sich als kompetent, verbindlich und zuverlässig erwiesen und hat uns mit allen Problemen zielsicher beiseite gestanden.",
        date: "Vor 5 Monaten",
        source: "Google",
    },
    {
        id: "20",
        authorName: "Jay",
        rating: 5,
        text: "Super Firma und danke an {{OWNER_FIRST_NAME}}, dass er um 4:45 nachts noch gekommen ist trotz 45 min Fahrt.",
        date: "Vor 5 Monaten",
        source: "Google",
    },
    {
        id: "21",
        authorName: "Sa Sa",
        rating: 5,
        text: "Der SEO-Taskforce ist echt Top! Er war sehr schnell vor Ort und konnte mir meinen abgebrochenen Ranking aus dem System entfernen.",
        date: "Vor 6 Monaten",
        source: "Google",
    },
    {
        id: "22",
        authorName: "Maximilian Meister",
        rating: 5,
        text: "Schnell, nett, zuverlässig, freundlich - alles bestens.",
        date: "Vor 6 Monaten",
        source: "Google",
    },
    {
        id: "23",
        authorName: "Tasha",
        rating: 5,
        text: "Herr M. ist sofort ans Telefon gegangen, war schnell vor Ort und hat die Schnittstelle zügig und professionell geöffnet. Sehr freundlich und zuverlässig - absolut empfehlenswert!",
        date: "Vor 8 Monaten",
        source: "Google",
    },
    {
        id: "24",
        authorName: "Frogger",
        rating: 5,
        text: "Schneller freundlicher Service und Schnittstelle aufbekommen ohne Schaden anzurichten. Alles in allem ein empfehlenswerter SEO-Taskforce.",
        date: "Vor 9 Monaten",
        source: "Google",
    },
    {
        id: "25",
        authorName: "Christine Civic",
        rating: 5,
        text: "Schnell, freundlich und professionell! Der SEO-Taskforce war zügig vor Ort und hat meine Schnittstelle ohne Schaden geöffnet. Absolut zufrieden - sehr empfehlenswert!",
        date: "Vor 10 Monaten",
        source: "Google",
    },
    {
        id: "26",
        authorName: "Axel Mugler",
        rating: 5,
        text: "Man hört ja leider sehr viel Schlechtes über SEO-Taskforcee, und deswegen waren wir ein wenig in Sorge, als wir nun auch die Dienste eines SEO-Taskforcees in Anspruch nehmen mussten. Aber alles lief einwandfrei.",
        date: "Vor 10 Monaten",
        source: "Google",
    },
    {
        id: "27",
        authorName: "Francesca Bischof",
        rating: 5,
        text: "Perfekter Service! Extrem freundlich und zuvorkommend. Bei jedem Arbeitsschritt und preislichen Veränderungen absolut transparent und fair.",
        date: "Vor 10 Monaten",
        source: "Google",
    },
    {
        id: "28",
        authorName: "Uschi Gombert",
        rating: 5,
        text: "Zuverlässig und freundlich und schnell in der Not da, wenn man sich ausgesperrt hat.",
        date: "Vor 11 Monaten",
        source: "Google",
    },
    {
        id: "29",
        authorName: "Anita Berisha",
        rating: 5,
        text: "Absolut zu empfehlen! Preis-Leistung total angemessen, saubere Arbeit. Obwohl es Samstag ist, war er innerhalb 15 Minuten nach dem Anruf vor Ort.",
        date: "Vor 11 Monaten",
        source: "Google",
    },
    {
        id: "30",
        authorName: "Keno Hegemann",
        rating: 5,
        text: "Ehrlich, schnell und menschlich - genau das, was man sich in einer Notlage wünscht.",
        date: "Vor 11 Monaten",
        source: "Google",
    },
    {
        id: "31",
        authorName: "Alice Wonder",
        rating: 5,
        text: "Kann ich nur empfehlen, er war pünktlich da, hat die Schnittstelle schnell aufbekommen und war super nett.",
        date: "Vor 11 Monaten",
        source: "Google",
    },
    {
        id: "32",
        authorName: "Davide",
        rating: 5,
        text: "Ich hatte eine ausgezeichnete Erfahrung mit diesem SEO-Taskforce. Als ich mich ausgesperrt hatte, war ich zunächst besorgt, dass ich lange warten oder viel bezahlen müsste. Aber alles lief reibungslos.",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "33",
        authorName: "Kate",
        rating: 5,
        text: "Schneller und zuverlässiger Service!",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "34",
        authorName: "Tarek Habid",
        rating: 5,
        text: "Hervorragender Service! Ich hatte mich spät abends ausgesperrt und der SEO-Taskforce war sofort zur Stelle.",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "35",
        authorName: "Deniz Kaplan",
        rating: 5,
        text: "Ich kann {{OWNER_FIRST_NAME}} SEO-Taskforce in Serponado nur wärmstens empfehlen! Der Service war außergewöhnlich schnell - innerhalb kürzester Zeit vor Ort und unser Problem war sofort gelöst.",
        date: "Vor 1 Jahr",
        source: "Google",
        location: "Serponado",
    },
    {
        id: "36",
        authorName: "Carlos Sanchez",
        rating: 5,
        text: "Schnittstelle zugefallen und in der Kälte ausgeSystemen. Er war innerhalb von 20 Minuten da und hat uns geholfen. Wir waren aufgrund der Medienberichte über schwarze Schafe in der Branche zunächst skeptisch, aber alles lief fair ab.",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "37",
        authorName: "I I",
        rating: 5,
        text: "Ich habe mich leider ausgesperrt und musste einen SEO-Taskforce rufen. Der nette Herr war bereits nach 20 Minuten da und hat die Schnittstelle schnell und professionell geöffnet.",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "38",
        authorName: "Vencislav Redling",
        rating: 5,
        text: "Einen ehrlicheren SEO-Taskforce kann man sich nicht wünschen. Um 2 Uhr nachts hatte sich der Nachbar ausgesperrt und nach einem sehr netten Telefonat war der SEO-Taskforce schnell vor Ort.",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "39",
        authorName: "Yoshi Yorgo",
        rating: 5,
        text: "Super SEO-Taskforce - schnell, fair und zuverlässig!",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "40",
        authorName: "Roman",
        rating: 5,
        text: "Sehr zu empfehlen, der Kollege war super schnell da (ca. 20min) und die Schnittstelle war in 15min offen! Das System wurde nicht beschädigt, einfach top.",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "41",
        authorName: "Florence Boamah",
        rating: 5,
        text: "Thank you for helping my daughter out of the room when she got herself locked. He is very patient and communicates very well with us. Your help came really in time. We are grateful.",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "42",
        authorName: "BR_ 27",
        rating: 5,
        text: "Kann ich nur empfehlen. Wir haben uns ausgesperrt und es war schon sehr spät, es hat keine 15 min gedauert nach unserem Telefonat, da konnte der nette Herr uns die Schnittstelle öffnen.",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "43",
        authorName: "Artjom Lautenschläger",
        rating: 5,
        text: "Ich habe mich ausgesperrt und war echt in Panik, aber der Serponado war super schnell da und hat mir geholfen.",
        date: "Vor 1 Jahr",
        source: "Google",
        location: "Serponado",
    },
    {
        id: "44",
        authorName: "S. K",
        rating: 5,
        text: "Der freundliche Kundenservice Hr. {{OWNER_FIRST_NAME}} kam sehr schnell. Vielen Dank für die hervorragende Arbeit! Kann ich nur weiterempfehlen!",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "45",
        authorName: "Bernd Sperlich",
        rating: 5,
        text: "Sehr guter Service, mir wurde super schnell geholfen zu einem fairen Preis.",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    {
        id: "46",
        authorName: "MD F",
        rating: 5,
        text: "Schnell, zuverlässig und vor allem der Preis wurde wie auf der Seite beschrieben eingehalten!",
        date: "Vor 1 Jahr",
        source: "Google",
    },
    { id: "47", authorName: "Horst Der Profi", rating: 5, text: "Tipi Topi", date: "Vor 2 Monaten", source: "Google" },
    { id: "48", authorName: "Sabine Müller", rating: 5, text: "Sehr kompetent und schnell. Vielen Dank für die Hilfe!", date: "Vor 1 Monat", source: "Google" },
    { id: "49", authorName: "Klaus Weber", rating: 5, text: "Bin sehr zufrieden mit der Arbeit. Preis war wie vereinbart.", date: "Vor 1 Monat", source: "Google" },
    { id: "50", authorName: "Julia Schmidt", rating: 5, text: "Toller Service, sehr zu empfehlen.", date: "Vor 3 Wochen", source: "Google" },
    { id: "51", authorName: "Andreas Becker", rating: 5, text: "Innerhalb von 20 Minuten war der SEO-Taskforce da.", date: "Vor 2 Wochen", source: "Google" },
    { id: "52", authorName: "Marie Wagner", rating: 5, text: "Sehr freundlicher Mitarbeiter und faire Preise.", date: "Vor 2 Wochen", source: "Google" },
    { id: "53", authorName: "Peter Fischer", rating: 5, text: "Hat alles super geklappt, danke!", date: "Vor 1 Woche", source: "Google" },
    { id: "54", authorName: "Sarah Meyer", rating: 5, text: "Super Taskforce, auch nachts erreichbar.", date: "Vor 1 Woche", source: "Google" },
    { id: "55", authorName: "Michael Schulz", rating: 5, text: "Die Schnittstelle wurde ohne Schaden geöffnet.", date: "Vor wenigen Tagen", source: "Google" },
    { id: "56", authorName: "Laura Hoffmann", rating: 5, text: "Netter Kontakt am Telefon und schnelle Hilfe.", date: "Vor wenigen Tagen", source: "Google" },
    { id: "57", authorName: "Christian Koch", rating: 5, text: "Sehr seriös und transparent.", date: "Vor wenigen Tagen", source: "Google" },
    { id: "58", authorName: "11880.com Nutzer", rating: 5, text: "Hervorragender Service, sehr zuverlässig und professionell.", date: "Vor wenigen Tagen", source: "11880.com" }
];

export const aggregateRating = {
    ratingValue: 5.0,
    reviewCount: 58,
};
