// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[stadtgebiet]" | "/agb" | "/anfrage" | "/barrierefreiheit" | "/bewertungen" | "/blog" | "/blog/[slug]" | "/cookie-richtlinie" | "/danke" | "/datenschutz" | "/dev/dashboard" | "/embed/einbruchrisiko" | "/emergency" | "/faq" | "/impressum" | "/kontakt" | "/leistungen" | "/leistungen/ai-content-sanierung" | "/leistungen/content-cannibalization" | "/leistungen/core-update-notdienst" | "/leistungen/eeat-audit" | "/leistungen/index-rettung" | "/leistungen/penalty-recovery" | "/leistungen/ranking-tresor" | "/leistungen/serponado-schild" | "/leistungen/snippet-optimierung" | "/leistungen/toxic-link-detox" | "/lexikon" | "/lexikon/[slug]" | "/preise" | "/preview" | "/preview-images" | "/ratgeber" | "/ratgeber/[slug]" | "/ratgeber/penalty-risiko" | "/referenzen" | "/referenzen/[slug]" | "/serponado" | "/serponado-agentur" | "/serponado/[slug]" | "/servicegebiet" | "/sitemap-uebersicht" | "/standorte/[poiSlug]" | "/termin-buchen" | "/ueber-uns" | "/ueber-uns/geschichte" | "/ueber-uns/karriere" | "/ueber-uns/philosophie" | "/ueber-uns/team" | "/widerruf"
type AppRouteHandlerRoutes = "/ai.txt" | "/api/consent-audit" | "/api/contact" | "/api/cron/video-syndication" | "/api/csp-report" | "/api/health" | "/api/markdown-mirror" | "/api/monitoring/errors" | "/api/og" | "/api/reviews" | "/api/serponado-index" | "/api/tracking" | "/llms-full.txt" | "/llms.txt" | "/sitemap-ai.xml"
type PageRoutes = never
type LayoutRoutes = "/" | "/dev/dashboard" | "/preview"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[stadtgebiet]": { "stadtgebiet": string; }
  "/agb": {}
  "/ai.txt": {}
  "/anfrage": {}
  "/api/consent-audit": {}
  "/api/contact": {}
  "/api/cron/video-syndication": {}
  "/api/csp-report": {}
  "/api/health": {}
  "/api/markdown-mirror": {}
  "/api/monitoring/errors": {}
  "/api/og": {}
  "/api/reviews": {}
  "/api/serponado-index": {}
  "/api/tracking": {}
  "/barrierefreiheit": {}
  "/bewertungen": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/cookie-richtlinie": {}
  "/danke": {}
  "/datenschutz": {}
  "/dev/dashboard": {}
  "/embed/einbruchrisiko": {}
  "/emergency": {}
  "/faq": {}
  "/impressum": {}
  "/kontakt": {}
  "/leistungen": {}
  "/leistungen/ai-content-sanierung": {}
  "/leistungen/content-cannibalization": {}
  "/leistungen/core-update-notdienst": {}
  "/leistungen/eeat-audit": {}
  "/leistungen/index-rettung": {}
  "/leistungen/penalty-recovery": {}
  "/leistungen/ranking-tresor": {}
  "/leistungen/serponado-schild": {}
  "/leistungen/snippet-optimierung": {}
  "/leistungen/toxic-link-detox": {}
  "/lexikon": {}
  "/lexikon/[slug]": { "slug": string; }
  "/llms-full.txt": {}
  "/llms.txt": {}
  "/preise": {}
  "/preview": {}
  "/preview-images": {}
  "/ratgeber": {}
  "/ratgeber/[slug]": { "slug": string; }
  "/ratgeber/penalty-risiko": {}
  "/referenzen": {}
  "/referenzen/[slug]": { "slug": string; }
  "/serponado": {}
  "/serponado-agentur": {}
  "/serponado/[slug]": { "slug": string; }
  "/servicegebiet": {}
  "/sitemap-ai.xml": {}
  "/sitemap-uebersicht": {}
  "/standorte/[poiSlug]": { "poiSlug": string; }
  "/termin-buchen": {}
  "/ueber-uns": {}
  "/ueber-uns/geschichte": {}
  "/ueber-uns/karriere": {}
  "/ueber-uns/philosophie": {}
  "/ueber-uns/team": {}
  "/widerruf": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dev/dashboard": never
  "/preview": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
