// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(legal)/agb/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agb">> = Specific
  const handler = {} as typeof import("../../app/(legal)/agb/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(legal)/barrierefreiheit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/barrierefreiheit">> = Specific
  const handler = {} as typeof import("../../app/(legal)/barrierefreiheit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(legal)/cookie-richtlinie/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cookie-richtlinie">> = Specific
  const handler = {} as typeof import("../../app/(legal)/cookie-richtlinie/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(legal)/datenschutz/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/datenschutz">> = Specific
  const handler = {} as typeof import("../../app/(legal)/datenschutz/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(legal)/impressum/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/impressum">> = Specific
  const handler = {} as typeof import("../../app/(legal)/impressum/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(legal)/widerruf/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/widerruf">> = Specific
  const handler = {} as typeof import("../../app/(legal)/widerruf/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/[stadtgebiet]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[stadtgebiet]">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/[stadtgebiet]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/anfrage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/anfrage">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/anfrage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/bewertungen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bewertungen">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/bewertungen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/danke/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/danke">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/danke/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/kontakt/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kontakt">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/kontakt/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/leistungen/ai-content-sanierung/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leistungen/ai-content-sanierung">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/leistungen/ai-content-sanierung/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/leistungen/content-cannibalization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leistungen/content-cannibalization">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/leistungen/content-cannibalization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/leistungen/core-update-notdienst/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leistungen/core-update-notdienst">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/leistungen/core-update-notdienst/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/leistungen/eeat-audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leistungen/eeat-audit">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/leistungen/eeat-audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/leistungen/index-rettung/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leistungen/index-rettung">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/leistungen/index-rettung/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/leistungen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leistungen">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/leistungen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/leistungen/penalty-recovery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leistungen/penalty-recovery">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/leistungen/penalty-recovery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/leistungen/ranking-tresor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leistungen/ranking-tresor">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/leistungen/ranking-tresor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/leistungen/serponado-schild/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leistungen/serponado-schild">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/leistungen/serponado-schild/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/leistungen/snippet-optimierung/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leistungen/snippet-optimierung">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/leistungen/snippet-optimierung/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/leistungen/toxic-link-detox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leistungen/toxic-link-detox">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/leistungen/toxic-link-detox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/lexikon/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lexikon/[slug]">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/lexikon/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/lexikon/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lexikon">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/lexikon/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/preise/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preise">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/preise/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/preview-images/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preview-images">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/preview-images/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/ratgeber/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ratgeber/[slug]">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/ratgeber/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/ratgeber/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ratgeber">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/ratgeber/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/ratgeber/penalty-risiko/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ratgeber/penalty-risiko">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/ratgeber/penalty-risiko/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/serponado-agentur/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/serponado-agentur">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/serponado-agentur/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/servicegebiet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servicegebiet">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/servicegebiet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/termin-buchen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/termin-buchen">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/termin-buchen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/ueber-uns/geschichte/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ueber-uns/geschichte">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/ueber-uns/geschichte/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/ueber-uns/karriere/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ueber-uns/karriere">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/ueber-uns/karriere/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/ueber-uns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ueber-uns">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/ueber-uns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/ueber-uns/philosophie/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ueber-uns/philosophie">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/ueber-uns/philosophie/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/ueber-uns/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ueber-uns/team">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/ueber-uns/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(panic)/emergency/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/emergency">> = Specific
  const handler = {} as typeof import("../../app/(panic)/emergency/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dev/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dev/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/embed/einbruchrisiko/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/embed/einbruchrisiko">> = Specific
  const handler = {} as typeof import("../../app/embed/einbruchrisiko/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preview">> = Specific
  const handler = {} as typeof import("../../app/preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/referenzen/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referenzen/[slug]">> = Specific
  const handler = {} as typeof import("../../app/referenzen/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/referenzen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referenzen">> = Specific
  const handler = {} as typeof import("../../app/referenzen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/serponado/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/serponado/[slug]">> = Specific
  const handler = {} as typeof import("../../app/serponado/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/serponado/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/serponado">> = Specific
  const handler = {} as typeof import("../../app/serponado/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sitemap-uebersicht/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sitemap-uebersicht">> = Specific
  const handler = {} as typeof import("../../app/sitemap-uebersicht/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/standorte/[poiSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/standorte/[poiSlug]">> = Specific
  const handler = {} as typeof import("../../app/standorte/[poiSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ai.txt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/ai.txt">> = Specific
  const handler = {} as typeof import("../../app/ai.txt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/consent-audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/consent-audit">> = Specific
  const handler = {} as typeof import("../../app/api/consent-audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/video-syndication/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/video-syndication">> = Specific
  const handler = {} as typeof import("../../app/api/cron/video-syndication/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/csp-report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/csp-report">> = Specific
  const handler = {} as typeof import("../../app/api/csp-report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/markdown-mirror/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/markdown-mirror">> = Specific
  const handler = {} as typeof import("../../app/api/markdown-mirror/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/monitoring/errors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/errors">> = Specific
  const handler = {} as typeof import("../../app/api/monitoring/errors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/og/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/og">> = Specific
  const handler = {} as typeof import("../../app/api/og/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reviews">> = Specific
  const handler = {} as typeof import("../../app/api/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/serponado-index/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/serponado-index">> = Specific
  const handler = {} as typeof import("../../app/api/serponado-index/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tracking/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tracking">> = Specific
  const handler = {} as typeof import("../../app/api/tracking/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/llms-full.txt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/llms-full.txt">> = Specific
  const handler = {} as typeof import("../../app/llms-full.txt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/llms.txt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/llms.txt">> = Specific
  const handler = {} as typeof import("../../app/llms.txt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sitemap-ai.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/sitemap-ai.xml">> = Specific
  const handler = {} as typeof import("../../app/sitemap-ai.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(legal)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(legal)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(panic)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(panic)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dev/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dev/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dev/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/preview/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/preview">> = Specific
  const handler = {} as typeof import("../../app/preview/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
